### ISSUE TITLE
error creating new blog entry

### ISSUE THREAD

**Issue by kp-org** [dokufreaks/plugin-blogtng#125]
I get the following error if I want to create a new page with the <blog newentry> function:

Failed to handle action: preview

Hitting the new page button afterwards creates the page, but it is not as nice as before. Maybe it is similar to https://github.com/splitbrain/dokuwiki/issues/2297.

blogtng version: 2018-05-04
dokuwiki version: greebo

**Comment by LarsGit223** [comment]
This should be fixed. Please re-install current version (even so there is no update message) and re-test.

**Comment by kp-org** [comment]
I did re-install the plugin and now it works. Thanks.

**Comment by LarsGit223** [comment]
Nice. Thanks for the quick response.
