### ISSUE TITLE
Declaration warning in comment.php

### ISSUE THREAD

**Issue by kp-org** [dokufreaks/plugin-blogtng#126]
With Greebo the log show the following warning:

`PHP Warning:  Declaration of renderer_plugin_blogtng_comment::plugin($name, $data) should be compatible with Doku_Renderer::plugin($name, $data, $state = '', $match = '') in dokuwiki-2018-04-22a/lib/plugins/blogtng/renderer/comment.php on line 13`

It happens at the  '&do=admin' page by click on Configuration Settings'.

**Comment by LarsGit223** [comment]
Should be fixed now.

**Comment by kp-org** [comment]
The warning is disappeared - thanks.
