### ISSUE TITLE
blogtng break default feed in dokuwiki 2011-05-25a

### ISSUE THREAD

**Issue by lainme** [dokufreaks/plugin-blogtng#65]
Today I updated my dokuwiki from Anteater to 2011-05-25a Rincewind, and find that the default feed behaves badly.

The feed for blogtng, eg. http://www.example.com/feed.php?mode=blogtng&blog=default is OK. 

But http://www.example.com/feed.php returns page with no article content(only article date actually)

**Comment by LarsGit223** [comment]
Can this be closed? Seems to be outdated...
