### ISSUE TITLE
Listings by Sqlite don't respect ACLs

### ISSUE THREAD

**Issue by michitux** [dokufreaks/plugin-blogtng#92]
When you assign a page to a blog it will be displayed in that blog listing regardless of the permissions of the page. I think this is an issue for several reasons:

* It would be nice to be able to create draft blog posts that are already part of the blog but are protected by ACLs and then publish them by changing the ACLs
* If you have a private part of the wiki with a private blog and somewhere a page that can be edited by users and these users can guess the name of the private blog, they will be able to see the listing of these entries (possibly with the whole content or a part of it).
* If you assign a private page to a blog (or the wrong blog) by accident it will be published (and you might not even notice the problem immediately as you assume that only users with enough permissions can see it in the list)

**Comment by Klap-in** [comment]
All the queries to sqlite-db are now checking per page the ACL.
